// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package main

import (
	"context"
)

const bookId1 = `-- name: BookId1 :one
SELECT id, title, description FROM books WHERE id = 1
`

func (q *Queries) BookId1(ctx context.Context) (Book, error) {
	row := q.db.QueryRowContext(ctx, bookId1)
	var i Book
	err := row.Scan(&i.ID, &i.Title, &i.Description)
	return i, err
}

const listBooks = `-- name: ListBooks :many
SELECT id, title, description FROM books
ORDER BY title
`

func (q *Queries) ListBooks(ctx context.Context) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, listBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(&i.ID, &i.Title, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
