// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package main

import (
	"database/sql"
)

type Book struct {
	ID          int64
	Title       sql.NullString
	Description sql.NullString
}
