// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type Author struct {
	ID        int64
	FirstName sql.NullString
	LastName  sql.NullString
}

type Book struct {
	ID          int64
	Title       sql.NullString
	Description sql.NullString
}

type Loan struct {
	ID         int64
	StartDate  sql.NullString
	ReturnDate sql.NullString
	DueDate    sql.NullString
}

type User struct {
	ID        int64
	FirstName sql.NullString
	LastName  sql.NullString
	Email     sql.NullString
	Username  sql.NullString
	Password  sql.NullString
	Role      sql.NullString
}
