// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Book struct {
	ID          int32
	Title       sql.NullString
	Description sql.NullString
}
